deploy:
  machine:
      enabled: true
  working_directory: ~/pilz-io
  environment:
  steps:
    - checkout
    - run:
        name: Setup Heroku
        command: bash .circleci/setup-heroku.sh

    - run:
        name: Deploy to host
        command: |
          rsync -av . circleci@pilz.io:/remote/dir/
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master